Updated release script to exit on subcommand failures.

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -1,4 +1,11 @@
 #!/usr/bin/env sh
+# exit when any command fails
+set -e
+
+# keep track of the last executed command
+trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
+# echo an error message before exiting
+trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT
 
 if output=$(git status --porcelain) && [ -z "$output" ]; then
   echo 'Checking out the master branch...'
